"""Builds the Operator Task Planner's input from the running app — read-only.

Consumes, never writes: the manager's published schedule (planning_store), the forecast generated by
weather.py, the existing ETA model output and baseline (Engine.eta_out, PlanningService.eta_baseline),
live telemetry/time accounting from LiveSim, the safety rule engine and the anomaly detector.
"""
from __future__ import annotations

from operator_metrics import shift_summary
from operator_planner import OperatorProductivityPlanner
from schedule_clock import ScheduleClock
from simulator import OPERATORS, TASK_TYPES
from weather import to_min

TASK_FIELDS = ("task_id", "name", "location", "task_type", "machine", "start", "end", "start_min", "end_min",
               "base_min", "effective_min", "delay_min")


def published_inputs(pub_tasks: list[dict], operator_id: str, baseline_fn) -> tuple[list[dict], dict]:
    """This operator's published entries in published order (copied, never mutated) + live expected
    durations = existing ETA model baseline x the manager planner's weather factor for that window."""
    tasks, expected = [], {}
    for e in sorted((e for e in pub_tasks if e["operator"] == operator_id), key=lambda e: e["start_min"]):
        snap = e["task"]
        rec = e.get("recommendation") or {}
        tasks.append({
            **{k: e[k] for k in TASK_FIELDS}, "label": TASK_TYPES[e["task_type"]]["label"],
            "weather_sensitivity": dict(e["weather_sensitivity"]), "tonnes": snap["tonnes"],
            "distance_m": snap["distance_m"], "terrain": snap["terrain"],
            "depends_on": list(snap.get("depends_on") or []),
            "recommendation": {k: rec.get(k) for k in ("label", "operator_note", "dominant_factor")},
        })
        wx = e["effective_min"] / e["base_min"] if e["base_min"] else 1.0
        expected[e["task_id"]] = baseline_fn(snap) * wx
    return tasks, expected


class OperatorPlannerService:
    def __init__(self, engine):
        self.engine = engine
        self.planner = OperatorProductivityPlanner()

    # ------------------------------------------------------------------ inputs
    def build_context(self, operator_id: str) -> dict:
        eng = self.engine
        with eng.lock:
            store = eng.planning.store
            pub, fc = store.published, store.forecast
            ctx = {"operator": {"id": operator_id, "name": OPERATORS[operator_id]["name"]},
                   "published": None, "tasks": [], "live_expected": {},
                   "forecast": {"hours": fc["hours"], "windows": fc["windows"], "summary": fc["summary"],
                                "label": fc["label"], "forecast_id": fc["forecast_id"]},
                   "shift": {"start": store.shift["start"], "end": store.shift["end"]},
                   "live": None, "other_operator": None}
            if pub:
                ctx["published"] = {k: pub[k] for k in ("schedule_id", "created_at", "manager_name")}
                ctx["tasks"], ctx["live_expected"] = published_inputs(pub["tasks"], operator_id, eng.planning.eta_baseline)
            sim = eng.sim
            if sim is not None and sim.operator_id == operator_id and (eng.shift.get("active") or eng.shift.get("ended")):
                ctx["live"] = self._live(operator_id)
            elif sim is not None and eng.shift.get("active"):
                ctx["other_operator"] = OPERATORS[sim.operator_id]["name"]
            return ctx

    def _live(self, operator_id: str) -> dict:
        eng, sim = self.engine, self.engine.sim
        start = eng.shift["started_at"]
        now = sim.now() if eng.shift.get("active") else (eng.shift.get("ended_at") or sim.now())

        def mins(dt):
            return (dt - start).total_seconds() / 60.0

        active = bool(eng.shift.get("active"))
        cur = sim.current_task if active else None
        status = {t["id"]: "done" if t["id"] in sim.task_finished else "active" if cur and t["id"] == cur["id"] else "pending"
                  for t in sim.tasks}
        by_id = {t["id"]: t for t in sim.tasks}
        base_cache: dict[tuple, float] = {}

        def baseline(task_id, weather):
            key = (task_id, weather)
            if key not in base_cache:
                base_cache[key] = eng.cycle_baseline(operator_id, by_id[task_id], weather)
            return base_cache[key]

        e = eng.eta_out
        idle_log = list(sim.idle_log)
        if sim.idle and sim.idle_since:
            idle_log.append({"start": sim.idle_since.strftime("%H:%M:%S"), "minutes": round(sim.idle_min, 1),
                             "task_id": sim.idle_task, "progress": sim.idle_progress, "ongoing": True})
        return {
            "active": active, "ended": bool(eng.shift.get("ended")), "clock": now.strftime("%H:%M:%S"),
            "elapsed_min": mins(now), "status": status, "current_task_id": cur["id"] if cur else None,
            "sim_task_ids": [t["id"] for t in sim.tasks],
            "task_started_min": {k: mins(v) for k, v in sim.task_started.items()},
            "task_finished_min": {k: mins(v) for k, v in sim.task_finished.items()},
            "progress": {t["id"]: sim.moved_t[t["id"]] / t["tonnes"] for t in sim.tasks},
            "eta": {"task_id": e["task_id"], "minutes_exact": e["minutes_exact"], "err_min": e["err_min"],
                    "finish": e["finish"]} if e and active else None,
            "machine": {"phase": sim.phase, "idle": sim.idle, "idle_min": sim.idle_min, "speed_kmh": sim.speed,
                        "weather": sim.weather, "seatbelt": sim.seatbelt},
            "safety": {"level": eng.safety_out["level"], "reasons": list(eng.safety_out["reasons"]),
                       "details": list(eng.safety_out["details"])},
            "anomaly": dict(eng.anomaly),
            "time_s": dict(sim.time_s), "task_time_s": {k: dict(v) for k, v in sim.task_time_s.items()},
            "cycles": {
                "current": [c["cycle_s"] for c in sim.cycle_log if cur and c["task_id"] == cur["id"]],
                "current_baseline_s": baseline(cur["id"], sim.weather) if cur else None,
                "shift": [(c["cycle_s"], baseline(c["task_id"], c.get("weather", "clear"))) for c in sim.cycle_log],
            },
            "idle_log": idle_log,
            "weather_changes": sum(1 for ev in eng.events if ev["kind"] == "weather" and ev.get("weather") != "clear"),
        }

    # ------------------------------------------------------------------ outputs
    def view(self, operator_id: str) -> dict:
        return self.planner.plan(self.build_context(operator_id))

    def shift_summary(self) -> dict:
        """End-of-shift productivity for the operator who ran the live shift."""
        eng = self.engine
        if eng.sim is None:
            return {"available": False}
        ctx = self.build_context(eng.sim.operator_id)
        clock = (ScheduleClock(ctx["tasks"], ctx["live_expected"], to_min(ctx["shift"]["start"]))
                 if ctx["tasks"] else None)
        return shift_summary(ctx["live"], ctx["tasks"], clock, eng.eta.err_min)
